### DISCUSSION TITLE
Usage of `--datagrid-virtual-mode`

### DISCUSSION THREAD

**Discussion by bradleygore** [perspective-dev/perspective#2804] [Q&A]
When reading through the codebase I see [this](https://github.com/finos/perspective/blob/b903fa052664d09c18c0ba4f5f1e2bc28957b137/packages/perspective-viewer-datagrid/src/js/model/create.js#L166C40-L166C63):

```js
    regular.setDataListener(
        createDataListener(this.parentElement).bind(model, regular),
        {
            virtual_mode:
                window
                    .getComputedStyle(regular)
                    .getPropertyValue("--datagrid-virtual-mode")
                    ?.trim() || "both",
        }
    );
```

If one wants to disable the virtualization, this seems to be the way to do it. However, I cannot seem to make it work properly. I've tried setting it as a css style rule, but that doesn't seem to work.

```css
perspective-data-grid {
    --datagrid-virtual-mode: 'none';
}

// I've also tried putting the rule on the `perspective-workspace` element, etc... 
// hoping it would cascade down, but still no go
```

Is there somewhere that describes how to use this mechanism?
